version: "3.6"
services:
  backend:
    container_name: backendcontainer
    image: edtech/backend
    restart: always
    build: ./backend
    ports:
      - 8081:8081
  database:
    container_name: databasecontainer
    image: edtech/database
    build: ./database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "ed_tech"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD: "12345678"
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - 3307:3306
  frontend:
    container_name: frontendcontainer
    image: edtech/frontend
    restart: always
    build: ./frontend
    ports:
      - 80:80
